# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GXTaskExecutorDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GXTaskExecutorDemo
  pod 'GXTaskExecutor', :path=>'../SDK'

  target 'GXTaskExecutorDemoTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'GXTaskExecutorDemoUITests' do
    # Pods for testing
  end

end
